import type { ReactNode } from 'react'
import {
  SiReact, SiTypescript, SiJavascript, SiPython, SiNextdotjs, SiNodedotjs,
  SiTailwindcss, SiCss, SiHtml5, SiVuedotjs, SiAngular, SiSvelte,
  SiDocker, SiKubernetes, SiGooglecloud, SiFirebase,
  SiPostgresql, SiMysql, SiMongodb, SiPrisma,
  SiGit, SiGithub, SiGitlab, SiFigma, SiVercel, SiNetlify,
  SiExpress, SiFastify, SiFlask, SiDjango, SiSpringboot,
  SiTensorflow, SiPytorch, SiOpenai, SiRust, SiGo, SiDeno,
  SiRedis, SiGraphql, SiApollographql, SiTrpc,
  SiJest, SiCypress, SiVitest,
  SiTailwindcss as SiBootstrap, SiVite, SiWebpack,
  SiLinux, SiFlutter, SiAndroid, SiApple,
  SiSlack, SiNotion, SiJira,
  SiPhp, SiLaravel,
} from 'react-icons/si'
import { DiJava, DiScala, DiAws } from 'react-icons/di'
import { TbApi } from 'react-icons/tb'

const iconMap: Record<string, ReactNode> = {
  react: <SiReact className="text-blue-500" />,
  reactjs: <SiReact className="text-blue-500" />,
  vue: <SiVuedotjs className="text-green-500" />,
  vuejs: <SiVuedotjs className="text-green-500" />,
  angular: <SiAngular className="text-red-500" />,
  svelte: <SiSvelte className="text-orange-500" />,
  nextjs: <SiNextdotjs />,
  'next.js': <SiNextdotjs />,
  nodejs: <SiNodedotjs className="text-green-600" />,
  'node.js': <SiNodedotjs className="text-green-600" />,
  express: <SiExpress />,
  fastify: <SiFastify />,
  flask: <SiFlask />,
  django: <SiDjango />,
  springboot: <SiSpringboot className="text-green-600" />,
  'spring boot': <SiSpringboot className="text-green-600" />,
  typescript: <SiTypescript className="text-blue-600" />,
  javascript: <SiJavascript className="text-yellow-400" />,
  python: <SiPython className="text-blue-500" />,
  php: <SiPhp className="text-indigo-500" />,
  laravel: <SiLaravel className="text-red-500" />,
  'rest api': <TbApi className="text-emerald-600" />,
  java: <DiJava className="text-red-500" />,
  scala: <DiScala />,
  go: <SiGo className="text-cyan-500" />,
  golang: <SiGo className="text-cyan-500" />,
  rust: <SiRust className="text-orange-600" />,
  deno: <SiDeno />,
  tailwind: <SiTailwindcss className="text-teal-400" />,
  tailwindcss: <SiTailwindcss className="text-teal-400" />,
  css: <SiCss className="text-blue-500" />,
  html: <SiHtml5 className="text-orange-500" />,
  docker: <SiDocker className="text-blue-400" />,
  kubernetes: <SiKubernetes className="text-blue-600" />,
  aws: <DiAws />,
  'google cloud': <SiGooglecloud />,
  gcp: <SiGooglecloud />,
  firebase: <SiFirebase className="text-yellow-500" />,
  postgresql: <SiPostgresql className="text-blue-400" />,
  postgres: <SiPostgresql className="text-blue-400" />,
  mysql: <SiMysql className="text-blue-500" />,
  mongodb: <SiMongodb className="text-green-500" />,
  prisma: <SiPrisma />,
  redis: <SiRedis className="text-red-500" />,
  graphql: <SiGraphql className="text-pink-500" />,
  apollo: <SiApollographql />,
  trpc: <SiTrpc />,
  git: <SiGit className="text-orange-500" />,
  github: <SiGithub />,
  gitlab: <SiGitlab className="text-orange-500" />,
  figma: <SiFigma />,
  vercel: <SiVercel />,
  netlify: <SiNetlify className="text-teal-500" />,
  vite: <SiVite className="text-purple-500" />,
  webpack: <SiWebpack className="text-blue-500" />,
  jest: <SiJest className="text-red-400" />,
  cypress: <SiCypress />,
  vitest: <SiVitest className="text-green-500" />,
  playwright: <SiVitest className="text-green-500" />,
  bootstrap: <SiBootstrap className="text-purple-500" />,
  tensorflow: <SiTensorflow className="text-orange-500" />,
  pytorch: <SiPytorch className="text-red-500" />,
  openai: <SiOpenai className="text-green-500" />,
  linux: <SiLinux />,
  flutter: <SiFlutter className="text-blue-400" />,
  android: <SiAndroid className="text-green-500" />,
  ios: <SiApple />,
  slack: <SiSlack className="text-purple-500" />,
  notion: <SiNotion />,
  jira: <SiJira className="text-blue-500" />,
}

export function getTechIcon(name: string): ReactNode | null {
  return iconMap[name.toLowerCase().trim()] ?? null
}

export default iconMap
